spring.application.name=pixelforge-nexus
spring.data.mongodb.uri=mongodb://localhost:27017/pixelforge
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8080
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=strict
spring.thymeleaf.cache=false
spring.thymeleaf.check-template-location=true
